export {
  ArrowIcon,
  MenuIcon,
  LogoIcon,
  LineIcon,
  TeacherStudentIcon,
  TeacherStudent2Icon,
  OrnamentIcon,
  Nis1Icon,
  Nis2Icon,
  Nis3Icon,
  Nis4Icon,
  FooterLineIcon,
  LocationIconComponent,
  PhoneIconComponent,
  FacebookIconComponent,
  TwitterIconComponent,
  LinkedInIconComponent,
  InstagramIconComponent,
  LogoTransparentIcon,
  AboutUsHeroIcon,
  CommentIconComponent,
  MissionIconComponent,
  VisionIconComponent,
  ArrowUpIconComponent,
  ArrowUpWhiteIconComponent,
} from "./Icons";
